<?php

namespace App\Constants;

class Accounts
{
    const MOTOR_VEHICLE_FUEL_LUBRICANTS_ACCOUNT = '6120301';
    const MOTOR_VEHICLE_MAINTENANCE_ACCOUNT = '6120013';
    const MOTOR_VEHICLE_PROJECTS_FUEL_ACCOUNT = '1196000';
}
